# Generated by Django 3.2.25 on 2024-03-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
