# Generated by Django 3.2.25 on 2024-03-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0006_guanzhu_liking_pinglun_shoucang'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinglun',
            name='content',
            field=models.CharField(default='', max_length=255),
        ),
    ]
