# Generated by Django 3.2.25 on 2024-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0007_pinglun_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
                ('category', models.IntegerField(default=0)),
                ('sub_title', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
