# Generated by Django 3.2.25 on 2024-03-20 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0008_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
