# Generated by Django 3.2.25 on 2024-04-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0012_show_ji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show_Wen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Wen_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('src', models.CharField(default='', max_length=255)),
                ('vice_src', models.CharField(default='', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wqqweb.show_wen')),
            ],
        ),
    ]
