# Generated by Django 3.2.25 on 2024-04-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0013_show_wen_wen_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='wen_table',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
