# Generated by Django 3.2.25 on 2024-04-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0014_wen_table_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='show_wen',
            name='type_id',
            field=models.IntegerField(default=0),
        ),
    ]
