# Generated by Django 3.2.25 on 2024-04-12 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0015_show_wen_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wen_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wqqweb.wen_table')),
            ],
        ),
    ]
