# Generated by Django 3.2.25 on 2024-05-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0017_material_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
    ]
