# Generated by Django 3.2.25 on 2024-05-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0018_auto_20240508_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sub_content',
            field=models.TextField(default=''),
        ),
    ]
