# Generated by Django 3.2.25 on 2024-05-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0019_news_sub_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workman',
            name='honor',
            field=models.TextField(default='', max_length=255),
        ),
    ]
