# Generated by Django 3.2.25 on 2024-05-09 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0020_alter_workman_honor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workman',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workman',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
