# Generated by Django 3.2.25 on 2024-05-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0021_auto_20240509_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='workman',
            name='img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
