# Generated by Django 3.2.25 on 2024-05-09 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0022_workman_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workman',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
