# Generated by Django 3.2.25 on 2024-05-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0023_alter_workman_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='workman',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
