# Generated by Django 3.2.25 on 2024-05-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0024_workman_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workman',
            name='koutu',
            field=models.CharField(default='', max_length=255),
        ),
    ]
