# Generated by Django 3.2.25 on 2024-05-11 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0025_workman_koutu'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_time', models.DateField(auto_now_add=True)),
                ('range', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('contact', models.CharField(default='', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wqqweb.workman')),
            ],
        ),
    ]
