# Generated by Django 3.2.25 on 2024-05-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0026_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
