# Generated by Django 3.2.25 on 2024-05-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0030_interview_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_detail',
            name='main_category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
