# Generated by Django 3.2.25 on 2024-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0031_material_detail_main_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(default='', max_length=255)),
                ('describe', models.TextField(default='')),
                ('title', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
