# Generated by Django 3.2.25 on 2024-05-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0032_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='flag',
            field=models.CharField(default='', max_length=255),
        ),
    ]
