# Generated by Django 3.2.25 on 2024-05-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0034_history_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='type_id',
            field=models.IntegerField(default=0),
        ),
    ]
