# Generated by Django 3.2.25 on 2024-05-18 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0035_alter_history_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('sizes', models.CharField(default='', max_length=255)),
                ('child_list', models.TextField(default='')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wqqweb.goods')),
            ],
        ),
        migrations.CreateModel(
            name='goodsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('size', models.CharField(default='', max_length=255)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wqqweb.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
