# Generated by Django 3.2.25 on 2024-05-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wqqweb', '0038_remove_goodsinformation_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscomment',
            name='prices',
        ),
        migrations.AddField(
            model_name='goodsinformation',
            name='prices',
            field=models.CharField(default='', max_length=255),
        ),
    ]
